FROM --platform=$BUILDPLATFORM golang:1.21-alpine AS builder

# Install our build tools
RUN apk add --update ca-certificates
RUN echo "nonroot:x:1337:1337:nonroot:/nonroot:/usr/sbin/nologin" > /etc_passwd

FROM --platform=$BUILDPLATFORM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc_passwd /etc/passwd

USER nonroot

COPY example-app /
ENTRYPOINT ["/example-app"]
