version: '3.7'

services:
  app:
    container_name: app
    image: example-app:local
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/postgres?sslmode=disable"
      # DATABASE_CONFIG_FILE: "/config/database.yml"
    ports:
      - "8080:8080"
    volumes:
      - ./config/:/config
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}
