### Health endpoint

GET http://localhost:8080/healthz

### Readiness endpoint

GET http://localhost:8080/readyz

### List notes

GET http://localhost:8080/notes

### Create note

POST http://localhost:8080/notes HTTP/1.1
content-type: application/json

{
  "title": "title",
  "content": "test-Content"
}

### Update note

PUT http://localhost:8080/notes/1 HTTP/1.1
content-type: application/json

{
  "title": "new-title2",
  "content": "test-Content - new"
}


### Get node

GET http://localhost:8080/notes/1 HTTP/1.1
content-type: application/json

### Delete node

DELETE http://localhost:8080/notes/1 HTTP/1.1
content-type: application/json
