
GET http://localhost:8080/healthz

###

GET http://localhost:8080/notes

###

POST http://localhost:8080/notes HTTP/1.1
content-type: application/json

{
  "title": "title",
  "content": "test-Content"
}

###

GET http://localhost:8080/notes/1 HTTP/1.1
content-type: application/json

### 

DELETE http://localhost:8080/notes/1 HTTP/1.1
content-type: application/json
