bitnamipostgres:
  enabled: false
cnpgdb:
  enabled: true
  storage:
    storageClass: proxmox-data-ephemeral
  bootstrap:
    initdb: {}
  #  WAL backups isabled until it works: https://github.com/cloudnative-pg/cloudnative-pg/issues/3819
  backup: null
  #    barmanObjectStore:
  #      destinationPath: s3://example-app-dev-postgres-backup/
  scheduleBackups: []


