on:
  push:
    paths-ignore:
      - 'charts/**'
      - 'example/**'
      - 'docs/**'
      - '/*.md'
      - 'tests.rest'
    branches:
      - '*'
  pull_request:
    paths-ignore:
      - 'example/**'
      - 'charts/**'
      - 'docs/**'
      - '/*.md'
      - 'tests.rest'
  workflow_call:

name: Build and test
jobs:
  build:
    strategy:
      matrix:
        architecture: [amd64, arm64]
        os: [linux, darwin]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
        id: go

      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{matrix.architecture}} go build ${{ env.LDFLAGS }} -o bin/app-${{ matrix.os }}-${{ matrix.architecture }} github.com/camaeel/example-app/cmd/app

      - name: Test
        run: |
          # go get github.com/golang/mock/mockgen
          # go install github.com/golang/mock/mockgen
          go generate ./...
          go test ./...

      - uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          name: release-binaries-{{  matrix.os }}-{{ matrix.architecture }}
          path: bin/app-*
          if-no-files-found: error
