name: build
on:
  push:
    branches:
      - "master"
      - "main"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 7 * * 6'
  workflow_call:

jobs:
  build:
    name: Trivy vulnerability scanner
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Run Trivy vulnerability scanner in repo mode - non schedule & non master
        if: "${{ github.event }} != 'schedule' && ${{ github.event }} != 'push' || ${{ github.event }} == 'push' && ${{ github.ref_name }} != ${{ github.event.repository.default_branch }}"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true # we want to have full report
          severity: 'CRITICAL,HIGH' #report all severities
          exit-code: '1'
        
      - name: Run Trivy vulnerability scanner in repo mode - schedule & master
        if: "${{ github.event }} == 'schedule' || ${{ github.event }} == 'push' && ${{ github.ref_name }} == ${{ github.event.repository.default_branch }}"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          #ignore-unfixed: true # we want to have full report
          format: 'sarif'
          output: 'trivy-results.sarif'
          #severity: 'CRITICAL,HIGH' #report all severities
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab
        if: "${{ github.event }} == 'schedule' || ${{ github.event }} == 'push' && ${{ github.ref_name }} == ${{ github.event.repository.default_branch }}"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'