name: build
on:
  push:
    branches:
      - "master"
      - "main"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 2 * * 6'
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          #ignore-unfixed: true # we want to have full report
          format: 'sarif'
          output: 'trivy-results.sarif'
          #severity: 'CRITICAL,HIGH' #report all severities
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'